In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
## SENTENCES

sent = ['the glass of milk',
        'the glass of juice',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']
sent        

['the glass of milk',
 'the glass of juice',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
# Define the vocabulary size

voc_size = 10000

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## ONE HOT represenation for every word

one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[652, 8840, 8252, 9764],
 [652, 8840, 8252, 8680],
 [7838, 4174, 4651, 3598, 7642],
 [7838, 4174, 4651, 3598, 2575],
 [1531, 652, 8206, 8252, 8622],
 [463, 2715, 5052, 3598]]

In [6]:
## WORD EMBEDDING REPRESENTATION

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [ ]:
# making the vector of size 8 each

sent_len = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0  652 8840 8252 9764]
 [   0    0    0    0  652 8840 8252 8680]
 [   0    0    0 7838 4174 4651 3598 7642]
 [   0    0    0 7838 4174 4651 3598 2575]
 [   0    0    0 1531  652 8206 8252 8622]
 [   0    0    0    0  463 2715 5052 3598]]


In [9]:
## FEature representation

dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

e:\GenAI\NLP\ANN Classification\venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step


array([[[-0.00304789,  0.03494722, -0.0056874 ,  0.00409993,
         -0.01648511,  0.02879994, -0.00383629,  0.04061118,
          0.01940716, -0.01226331],
        [-0.00304789,  0.03494722, -0.0056874 ,  0.00409993,
         -0.01648511,  0.02879994, -0.00383629,  0.04061118,
          0.01940716, -0.01226331],
        [-0.00304789,  0.03494722, -0.0056874 ,  0.00409993,
         -0.01648511,  0.02879994, -0.00383629,  0.04061118,
          0.01940716, -0.01226331],
        [-0.00304789,  0.03494722, -0.0056874 ,  0.00409993,
         -0.01648511,  0.02879994, -0.00383629,  0.04061118,
          0.01940716, -0.01226331],
        [-0.01572385,  0.00038566,  0.02063045,  0.04754328,
         -0.04566479,  0.03878002,  0.04487575,  0.03634608,
         -0.0412764 , -0.00746343],
        [ 0.04085294, -0.03857342,  0.04471921,  0.00327463,
         -0.01900934, -0.01071857,  0.0354252 , -0.02466585,
          0.02447988, -0.02418203],
        [-0.00159823,  0.04775692, -0.01487417, -0.0

In [ ]:
## SO THIS IS HOW THE EMBEDDING LAYER WORKSS

model.predict(embedded_docs[0].reshape(1, -1))  

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step


array([[[-0.00304789,  0.03494722, -0.0056874 ,  0.00409993,
         -0.01648511,  0.02879994, -0.00383629,  0.04061118,
          0.01940716, -0.01226331],
        [-0.00304789,  0.03494722, -0.0056874 ,  0.00409993,
         -0.01648511,  0.02879994, -0.00383629,  0.04061118,
          0.01940716, -0.01226331],
        [-0.00304789,  0.03494722, -0.0056874 ,  0.00409993,
         -0.01648511,  0.02879994, -0.00383629,  0.04061118,
          0.01940716, -0.01226331],
        [-0.00304789,  0.03494722, -0.0056874 ,  0.00409993,
         -0.01648511,  0.02879994, -0.00383629,  0.04061118,
          0.01940716, -0.01226331],
        [-0.01572385,  0.00038566,  0.02063045,  0.04754328,
         -0.04566479,  0.03878002,  0.04487575,  0.03634608,
         -0.0412764 , -0.00746343],
        [ 0.04085294, -0.03857342,  0.04471921,  0.00327463,
         -0.01900934, -0.01071857,  0.0354252 , -0.02466585,
          0.02447988, -0.02418203],
        [-0.00159823,  0.04775692, -0.01487417, -0.0